ALTER TABLE [LookupData].[DependencyType]
    ADD CONSTRAINT [PK_DependencyType] PRIMARY KEY CLUSTERED ([DependencyTypeID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

