ALTER TABLE [LookupData].[ParameterType]
    ADD CONSTRAINT [PK_ParameterType] PRIMARY KEY CLUSTERED ([ParameterTypeID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

