ALTER TABLE [LogicData].[ActionGroup]
    ADD CONSTRAINT [PK_ActionGroup] PRIMARY KEY CLUSTERED ([ActionGroupID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

