ALTER TABLE [LogicData].[Command]
    ADD CONSTRAINT [PK_Command] PRIMARY KEY CLUSTERED ([CommandID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

