ALTER TABLE [LogicData].[CommandAction]
    ADD CONSTRAINT [PK_CommandAction] PRIMARY KEY CLUSTERED ([CommandActionID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

