ALTER TABLE [LogicData].[CommandActionParameter]
    ADD CONSTRAINT [PK_CommandActionParameter] PRIMARY KEY CLUSTERED ([CommandActionParameterID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

