ALTER TABLE [LogicData].[CommandActionResponse]
    ADD CONSTRAINT [PK_CommandTypeDirectionResponse] PRIMARY KEY CLUSTERED ([CommandActionResponseID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

