ALTER TABLE [LogicData].[Dependency]
    ADD CONSTRAINT [PK_Dependency] PRIMARY KEY CLUSTERED ([DependencyID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

