ALTER TABLE [LocationData].[LocationItem]
    ADD CONSTRAINT [PK_LocationItem] PRIMARY KEY CLUSTERED ([LocationID] ASC, [ItemID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

