<?xml version="1.0" encoding="utf-8"?><Database Name="Adventure" Class="GameDataDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(local)\sqlexpress;Initial Catalog=Adventure;Integrated Security=True" SettingsObjectName="Maskell.Adventure.DataAccess.GameData.Properties.Settings" SettingsPropertyName="AdventureConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="LocationData.Location" Member="Locations">
    <Type Name="Location">
      <Column Name="LocationID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GameID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="LocationName" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="LocationDescription" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="Location_Game" Member="Games" ThisKey="LocationID" OtherKey="StartLocationID" Type="Game" />
      <Association Name="Location_LocationDirection" Member="LocationDirections" ThisKey="LocationID" OtherKey="SourceLocationID" Type="LocationDirection" />
      <Association Name="Game_Location" Member="Game" ThisKey="GameID" OtherKey="GameID" Type="Game" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="GameData.Game" Member="Games">
    <Type Name="Game">
      <Column Name="GameID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="OwnerID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="DateAdded" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="StartLocationID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Association Name="Game_Location" Member="Locations" ThisKey="GameID" OtherKey="GameID" Type="Location" />
      <Association Name="Location_Game" Member="Location" ThisKey="StartLocationID" OtherKey="LocationID" Type="Location" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="LocationData.LocationDirection" Member="LocationDirections">
    <Type Name="LocationDirection">
      <Column Name="SourceLocationID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TargetLocationID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DirectionID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Location_LocationDirection" Member="Location" ThisKey="SourceLocationID" OtherKey="LocationID" Type="Location" IsForeignKey="true" />
      <Association Name="Direction_LocationDirection" Member="Direction" ThisKey="DirectionID" OtherKey="DirectionID" Type="Direction" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="LogicData.Command" Member="Commands">
    <Type Name="Command">
      <Column Name="CommandID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CommandTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FirstParameterType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SecondParameterType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ThirdParameterType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FourthParameterType" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="LocationData.Direction" Member="Directions">
    <Type Name="Direction">
      <Column Name="DirectionID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DirectionName" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="ShortName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Direction_LocationDirection" Member="LocationDirections" ThisKey="DirectionID" OtherKey="DirectionID" Type="LocationDirection" />
    </Type>
  </Table>
</Database>