/****** Object:  Table [LookupData].[CommandType]    Script Date: 10/13/2011 11:34:51 ******/
INSERT [LookupData].[CommandType] ([CommandTypeID], [CommandTypeName]) VALUES (1, N'close ')
INSERT [LookupData].[CommandType] ([CommandTypeID], [CommandTypeName]) VALUES (2, N'drink ')
INSERT [LookupData].[CommandType] ([CommandTypeID], [CommandTypeName]) VALUES (3, N'drop ')
INSERT [LookupData].[CommandType] ([CommandTypeID], [CommandTypeName]) VALUES (4, N'eat ')
INSERT [LookupData].[CommandType] ([CommandTypeID], [CommandTypeName]) VALUES (5, N'examine')
INSERT [LookupData].[CommandType] ([CommandTypeID], [CommandTypeName]) VALUES (6, N'give')
INSERT [LookupData].[CommandType] ([CommandTypeID], [CommandTypeName]) VALUES (7, N'go ')
INSERT [LookupData].[CommandType] ([CommandTypeID], [CommandTypeName]) VALUES (8, N'lock ')
INSERT [LookupData].[CommandType] ([CommandTypeID], [CommandTypeName]) VALUES (9, N'look')
INSERT [LookupData].[CommandType] ([CommandTypeID], [CommandTypeName]) VALUES (10, N'open ')
INSERT [LookupData].[CommandType] ([CommandTypeID], [CommandTypeName]) VALUES (11, N'pickup ')
INSERT [LookupData].[CommandType] ([CommandTypeID], [CommandTypeName]) VALUES (12, N'put ')
INSERT [LookupData].[CommandType] ([CommandTypeID], [CommandTypeName]) VALUES (13, N'take')
INSERT [LookupData].[CommandType] ([CommandTypeID], [CommandTypeName]) VALUES (14, N'talk ')
INSERT [LookupData].[CommandType] ([CommandTypeID], [CommandTypeName]) VALUES (15, N'unlock ')
INSERT [LookupData].[CommandType] ([CommandTypeID], [CommandTypeName]) VALUES (16, N'use')
